
module.exports = {
  'n/a': 'n/a',
  1: 'Applied Computational Mathematics (ACM)',
  2: 'Applied Physics and Mathematics',
  3: 'Astroparticle Physics',
  4: 'Attitude Formation',
  5: 'Biochemical Engineering',
  6: 'Biochemistry',
  7: 'Biochemistry and Cell Biology (BCCB)',
  8: 'Bioinformatics and Computational Biology',
  9: 'Biological Recognition',
  10: 'Biology',
  11: 'Biology/Neuroscience',
  12: 'Biotechnology',
  13: 'Buisness Administration',
  14: 'Chemistry',
  15: 'Communications',
  16: 'Comparative PolitIcs and Sociology',
  17: 'Computer Science',
  18: 'Earth and Space Sciences',
  19: 'Electrical Engineering and Computer Science',
  20: 'European Utility Management',
  21: 'Geo-Ocean Dynamics',
  22: 'Geosciences and Astrophysics',
  23: 'Global Economics and Management (GEM)',
  24: 'Global Visual Communication',
  25: 'History',
  26: 'History and Theory of Art and Literature',
  27: 'Humanities',
  28: 'Information Management and Systems (IMS)',
  29: 'Integrated Cultural Studies',
  30: 'Integrated Environmental Studies',
  31: 'Integrated Social and Cognitive Psychology (ISCP)',
  32: 'Integrated Social Sciences',
  33: 'Intercultural Humanities',
  34: 'Intercultural Relations and Behaviour (IRB)',
  35: 'International Communication',
  36: 'International History and Politics',
  37: 'International Logistics Engineering and Management (ILME)',
  38: 'International Politics and History (IPH)',
  39: 'International Relations',
  40: 'Life-Course and Lifespan Dynamics',
  41: 'Lifelong Learning',
  42: 'Marine Microbiology',
  43: 'Mathematics',
  44: 'Modern Global History',
  45: 'Molecular Life Science',
  46: 'Nanomolecular Sciences',
  47: 'Neuroscience',
  48: 'Physics',
  49: 'Political Economy &amp; Public Policy',
  50: 'Productive Adult Development',
  51: 'Psychology',
  52: 'Smart Systems',
  53: 'Visual Communication and Expertise'
}